config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :shoppings
  resources :e_stores
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#home'
  devise_for :users
  resources :bookings

  Rails.application.routes.draw do
    resources :orders, only: [:create, :show, :destroy]
  end

  get 'cart_item_count', to: 'carts#item_count'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Route for "/aboutus"
  get '/aboutus', to: 'pages#aboutus'
  get '/home', to: 'pages#home'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/shopping.rb
class Shopping < ApplicationRecord
  before_destroy :not_referenced_by_any_line_item
  belongs_to :user, optional: true
  has_many :line_items
  mount_uploader :image, ImageUploader
  serialize :image, JSON
  has_many :order_items
  has_many :orders, through: :order_items

  validate :name, :category
  validates :description, length: { maximum: 1000, too_long: "%{count} characters is the maximum aloud. "}
  validates :name, length: { maximum: 140, too_long: "%{count} characters is the maximum aloud. "}
  validates :price, length: { maximum: 7 }

  private

  def not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line items present")
      throw :abort
    end
  end
end

app/controllers/shoppings_controller.rb
class ShoppingsController < ApplicationController
  before_action :set_shopping, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /shoppings or /shoppings.json
  def index
    @shoppings = Shopping.all.order("created_at desc")
  end

  # GET /shoppings/1 or /shoppings/1.json
  def show
  end

  # GET /shoppings/new
  def new
    if current_user.admin?
      @shopping = Shopping.new
    else
      redirect_to root_path, alert: "You are not authorized to create."
    end
  end

  # GET /shoppings/1/edit
  def edit
  end

  # POST /shoppings or /shoppings.json
  def create
    if current_user.admin?
      @shopping = Shopping.new(shopping_params)

      respond_to do |format|
        if @shopping.save
          format.html { redirect_to shopping_url(@shopping), notice: "Shopping was successfully created." }
          format.json { render :show, status: :created, location: @shopping }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @shopping.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path, alert: "You are not authorized to create."
    end
  end

  # PATCH/PUT /shoppings/1 or /shoppings/1.json
  def update
    if current_user.admin?
      respond_to do |format|
        if @shopping.update(shopping_params)
          format.html { redirect_to shopping_url(@shopping), notice: "Shopping was successfully updated." }
          format.json { render :show, status: :ok, location: @shopping }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @shopping.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path, alert: "You are not authorized to update."
    end
  end

  # DELETE /shoppings/1 or /shoppings/1.json
  def destroy
    if current_user.admin?
      @shopping.destroy

      respond_to do |format|
        format.html { redirect_to shoppings_url, notice: "Shopping was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      redirect_to root_path, alert: "You are not authorized to delete."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopping
      @shopping = Shopping.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shopping_params
      params.require(:shopping).permit(:name, :description, :category, :price, :image)
    end
end

app/helpers/shoppings_helper.rb
module ShoppingsHelper
end

app/views/shoppings/_form.html.erb
<%= simple_form_for(@shopping) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, class: "form-control" %>
    <%= f.input :description, class: "form-control" %>
    <%= f.input :category, class: "form-control" %>
    <%= f.input :price, class: "form-control" %>
    <%= f.input :image, class: "form-control" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

<style>
  /* Form Container */
  .form-inputs {
    margin-bottom: 20px;
     font-family: 'Comic Sans MS', cursive;
  }

  /* Form Input Style */
  .form-control {
    width: 100%;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    margin-bottom: 10px;
  }

  /* Form Actions Container */
  .form-actions {
    display: flex;
    justify-content: flex-end;
  }

  /* Button Style */
  .btn {
    padding: 10px 20px;
    background-color: #007bff;
    border: none;
    border-radius: 4px;
    color: #fff;
    cursor: pointer;
  }

  .btn:hover {
    background-color: #0056b3;
  }
</style>

app/views/shoppings/_shopping.html.erb
<div class="card">
  <div class="card-content">
    <p class="title is-4"><strong>Name:</strong> <%= shopping.name %></p>
    <p><strong>Description:</strong> <%= shopping.description %></p>
    <p><strong>Category:</strong> <%= shopping.category %></p>
    <p><strong>Price:</strong> <%= shopping.price %></p>
    <p><strong>Image:</strong><%= image_tag(shopping.image_url(:default)) %></p>
  </div>
  <footer class="card-footer">
    <p class="card-footer-item">
      <%= button_to 'Add to cart', line_items_path(shopping_id: shopping.id), class: 'button is-warning add-to-cart' %>
    </p>
  </footer>
</div>

<style>
  .card {
    border-radius: 10px;
    box-shadow: 0 4px 6px rgba(1, 1, 1, 0.1);
    background-color: #black;
    padding: 20px;
  }

  .card-content {
    margin-bottom: 15px;
   
  }

  .card-footer {
    padding-top: 10px;
  }

  .button {
    border-radius: 4px;
    width:20px;
    padding: 10px 20px;
    font-size: 16px;
  }

  .is-warning {
   background-color: #294B29;
    color: white;
    border: none;
  }

  .add-to-cart {
    width: 100%;
    text-align: center;
  }
</style>

app/views/shoppings/edit.html.erb
<h1>Editing shopping</h1>

<%= render "form", shopping: @shopping %>

<br>

<div>
  <%= link_to "Show this shopping", @shopping %> |
  <%= link_to "Back to shoppings", shoppings_path %>
</div>

app/views/shoppings/index.html.erb
<style>
  #shoppings {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
  }

  .shopping-card {
    border-radius: 8px;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    background-color: #ffffff;
    padding: 20px;
    flex: 0 1 calc(33.33% - 20px);
    max-width: calc(33.33% - 20px);
    margin-bottom: 20px; /* Add some space between cards */
  }

  .shopping-card img {
    max-width: 100%;
    height: auto;
    border-radius: 8px;
    margin-bottom: 15px; /* Space between the image and the content */
  }

  .shopping-card-content {
    margin-bottom: 15px;
  }

  .shopping-card-footer {
    padding-top: 10px;
  }

  .button {
    border-radius: 4px;
    padding: 10px 20px;
    font-size: 16px;
  }

  .is-warning {
    background-color: #294B29;
    cursor: pointer;
    color: white;
    border: none;
  }

  .add-to-cart {
    width: 100%;
    text-align: center;
  }
</style>

<p style="color: green"><%= notice %></p>

<h1 style="text-align:center;">Shoppings</h1>

<div style="text-align:center; margin-top: 20px;">
  <button id="cart-count-button" class="button is-warning">
    Cart Items: <%= cart_item_count %>
  </button>
</div>

<div id="shoppings">
  <% @shoppings.each do |shopping| %>
    <div class="shopping-card">
      <img src="<%= shopping.image_url %>" alt="<%= shopping.name %> Image">
      <div class="shopping-card-content">
        <p class="title is-4"><strong>Name:</strong> <%= shopping.name %></p>
        <p><strong>Description:</strong> <%= shopping.description %></p>
        <p><strong>Category:</strong> <%= shopping.category %></p>
        <p><strong>Price:</strong> <%= shopping.price %></p>
     
      </div>
      <footer class="shopping-card-footer">
        <p class="card-footer-item">
          <%= button_to 'Add to cart', line_items_path(shopping_id: shopping.id), class: 'button is-warning add-to-cart' %>
        </p>
        <p>
            <% if current_user=="admin" %>
          <%= link_to "Show this shopping", shopping %>
          <%end%>
        </p>
      </footer>
    </div>
  <% end %>
</div>

<%= link_to "New shopping", new_shopping_path %>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        const cartCountButton = document.getElementById('cart-count-button');

        function updateCartCount() {
            fetch('/cart_item_count')
                .then(response => response.json())
                .then(data => {
                    cartCountButton.innerText = `Cart Items: ${data.count}`;
                })
                .catch(error => {
                    console.error('Error fetching cart item count:', error);
                });
        }

        if (cartCountButton) {
            updateCartCount(); // Initial load
            cartCountButton.addEventListener('click', updateCartCount);
        }
    });

</script>

app/views/shoppings/new.html.erb
<h1>New shopping</h1>

<%= render "form", shopping: @shopping %>

<br>

<div>
  <%= link_to "Back to shoppings", shoppings_path %>
</div>

app/views/shoppings/show.html.erb
<p style="color: green;"><%= notice %></p>

<%= render @shopping %>

<div style="display: flex; align-items: center; margin-top: 10px;">
  <%= link_to "Edit this shopping", edit_shopping_path(@shopping), class: "btn btn-primary", style: "margin-right: 10px; background-color: #294B29; padding:10px; color:white;text-decoration:none;" %>
  <%= link_to "Back to shoppings", shoppings_path, class: "btn btn-secondary", style: "margin-right: 10px;background-color: red; padding:10px; color:white;text-decoration:none;" %>
  <%= button_to "Destroy this shopping", @shopping, method: :delete, class: "btn btn-danger", style: "margin-right: 10px;background-color: blue; padding:10px; color:white;text-decoration:none;" %>
</div>
 