config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :shoppings
  resources :e_stores
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'pages#home'
  devise_for :users
  resources :bookings

  Rails.application.routes.draw do
    resources :orders, only: [:create, :show, :destroy]
  end

  get 'cart_item_count', to: 'carts#item_count'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Route for "/aboutus"
  get '/aboutus', to: 'pages#aboutus'
  get '/home', to: 'pages#home'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :shopping
  belongs_to :cart

  def total_price
    shopping.price.to_i * quantity.to_i
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_line_item, only: %i[ show edit update destroy ]
  before_action :set_cart, only: [:create]

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create
    shopping = Shopping.find(params[:shopping_id])
    @line_item = @cart.add_shopping(shopping)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart, notice: "Item added to cart" }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to line_item_url(@line_item), notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @cart = Cart.find(session[:cart_id])
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to cart_path(@cart), notice: "Line item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:shopping_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= simple_form_for(@line_item) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :shopping %>
    <%= f.association :cart %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<div class="row align-items-center mb-3" style="display: flex; align-items: center; margin-bottom: 1.5rem;">
  <div class="col-1" style="flex: 0 0 8.333333%; max-width: 8.333333%;">
    <%= line_item.quantity %>
  </div>
  <div class="col-2" style="flex: 0 0 16.666667%; max-width: 16.666667%;">
    <figure class="figure">
      <%# <%= image_tag(line_item.shopping.image_url(:thumb), class: "figure-img img-fluid rounded") %>
    </figure>
  </div>
  <div class="col-9" style="flex: 0 0 75%; max-width: 75%;">
    <strong><%= line_item.shopping.name %></strong>
    <div class="row align-items-center" style="display: flex; align-items: center;">
      <div class="col-9" style="flex: 0 0 75%; max-width: 50%;">
        <p class="mb-0" style="margin-bottom: 0;"><%= truncate(line_item.shopping.description, length: 140) %></p>
      </div>
      <div>
        <p><strong>Image:</strong><%= image_tag(line_item.shopping.image_url(:default)) %></p>
      </div>

      <div class="col-3 text-right" style="flex: 0 0 25%; max-width: 25%; text-align: right;">
        <strong><%= number_to_currency(line_item.total_price) %></strong>
      </div>
      <div class="text-right" style="text-align: right; margin-left: 40px;background-color: red; padding:8px; border-radius:10px; ">
        <%= link_to 'Remove Item', line_item, method: :delete, data: { confirm: "Are you sure? " }, class: "btn btn-sm btn-danger mb-4", style: "color: white; text-decoration:none;padding :18px; " %>
      </div>
    </div>
  </div>
</div>

<hr style="margin-top: 2rem; margin-bottom: 2rem;"/>

app/views/line_items/edit.html.erb
<h1>Editing line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Show this line item", @line_item %> |
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Line items</h1>

<div id="line_items">
  <% @line_items.each do |line_item| %>
    <%= render line_item %>
    <p>
      <%= link_to "Show this line item", line_item %>
    </p>
  <% end %>
</div>

<%= link_to "New line item", new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line item</h1>

<%= render "form", line_item: @line_item %>

<br>

<div>
  <%= link_to "Back to line items", line_items_path %>
</div>

app/views/line_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @line_item %>

<div>
  <%= link_to "Edit this line item", edit_line_item_path(@line_item) %> |
  <%= link_to "Back to line items", line_items_path %>

  <%= button_to "Destroy this line item", @line_item, method: :delete %>
</div>